[package]
name = "rustc-target-spirv"
description = "SPIR-V code generator backend for rustc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-tools = "0.10.0"

[package.metadata.rust-analyzer]
rustc_private = true
